name: first

on: push

jobs:
    job1:
        name: First Job
        runs-on: ubuntu-latest
        steps: 
          - run: date
          - run: time
    job2:
        name: Second Job
        runs-on: windows-latest
        steps:
         
          - run: date
          - run: time